# Generated by Django 5.1 on 2024-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='product',
            field=models.ManyToManyField(related_name='leads', to='App1.product'),
        ),
    ]
