# Generated by Django 5.1 on 2024-09-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_leads_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='leads_created',
        ),
    ]
